### ISSUE TITLE
Update build status from federalist builder

### ISSUE THREAD

**Issue by jmhooper** [18F/federalist-builder#15]
If Federalist builder fails to start a build for some reason, it should alert Federalist to the issue using the `STATUS_CALLBACK` variable in the container environment.

**Comment by jmhooper** [comment]
See 18F/federalist#737

**Comment by wslack** [comment]
Not done yet; build message says "completed successfully"

**Comment by wslack** [comment]
we're going to close this and leave Federalist #737 open
