### ISSUE TITLE
update healthcheck 

### ISSUE THREAD

**Issue by amirbey** [18F/federalist-builder#248]
#### User Story

<TODO>

#### Background (Optional)

The healtcheck was designed based on the health of the build containers.  Builds now run as tasks and measure of health should be updated accordingly

#### Acceptance Criteria

- [ ] <TODO>
- [ ] Change made live via <TODO>.

_After evaluating, edit this part:_

#### Implementation outline (if higher than "low" effort):

- [ ] <TODO>

**Comment by davemcorwin** [comment]
@amirbey we are now monitoring the queues for hold ups, does this suffice as a "healthcheck"?

**Comment by amirbey** [comment]
Yes. that is sufficient 👍
