### ISSUE TITLE
Healthcheck - add (estimate) of queued builds

### ISSUE THREAD

**Issue by jseppi** [18F/federalist-builder#61]
Add a new field to the healthcheck to report the estimated number of queued and running builds.

This is estimated because (from @jmhooper):

> You can get an approximation of messages in an SQS queue, but that number does not include messages have been read since the visibility timeout.
> Which means that if you have read a build and not executed on it within 5 or 10 seconds, it won’t appear in the approximation.

Refs:
- https://docs.aws.amazon.com/AWSSimpleQueueService/latest/APIReference/API_GetQueueAttributes.html

**Comment by el-mapache** [comment]
@jseppi I have a couple of questions I wanted to run by ya!

* Right now I have a fallback message if the AWS call returns an error, I don't think the healthcheck necessarily needs to fail if AWS doesn't respond for whatever reason.
  * Or maybe repeated failures could indicate an issue with AWS?

* How often do we want this function firing? Every couple of minutes? I think cloud.gov hits the health check endpoint pretty regularly so it would be a good idea to throttle the API call.

**Comment by el-mapache** [comment]
Speaking with James I've learned the following things!

* The health check end point gets called very intermittently so we don't need to worry about rate limiting at this point in time.

* A failure to get metadata from the queue *should* indicate an error with the builder, since the builder won't work properly without access to AWS.

**Comment by el-mapache** [comment]
Spoke with @seppi about this for a minute today and we're fairly certain the health check is failing because the IAM user doesn't have the getQueueAttributes scope/policy enabled. This will be blocked until we can get that added.

**Comment by jseppi** [comment]
Status: Working with Erik B to get the correct IAM permissions assigned.

**Comment by jseppi** [comment]
Erik has gotten the correct permissions assigned 🎉and I verified by issuing manual API requests locally.

There is unfortunately a bug our healthcheck code, but it will be quick to fix. I'll issue a PR soon.
