### ISSUE TITLE
Error reasons are doubly-stringified

### ISSUE THREAD

**Issue by jseppi** [18F/federalist-builder#71]
See:

```json 
{"ok":false,"reasons":["{\"error\":\"unauthorized\",\"error_description\":\"password change required\"}"]}
```

**Comment by wslack** [comment]
@jseppi where do users see this?

**Comment by jseppi** [comment]
This is on the federalist-builder healthcheck endpoint.

Typed up the issue from my phone and definitely didn't include enough context. Sorry!

**Comment by wslack** [comment]
all good! Assigning to you to add the context before triage - but only when back!

**Comment by wslack** [comment]
(especially the effort to fix - otherwise this seems less important since these aren't user facing)

**Comment by jseppi** [comment]
Extremely low effort to fix

**Comment by wslack** [comment]
dropped in ready then!

**Comment by jseppi** [comment]
Huh, turns out it is actually the error coming from CloudFoundry that is already json-stringified, not anything we're doing on our side of the code.  That is, the contents of `error.message` are `"{\"error\":\"unauthorized\",\"error_description\":\"password change required\"}"`

I think this should actually be kept as-is. We _could_ try parsing the `error.message` contents as JSON, but I think that's a little weird and I don't think there's a guarantee that those contents will always be valid JSON.

**Comment by jseppi** [comment]
While we could fix this, it's a little more than "extremely low" effort (still would be "low"), so I'm not sure how we want to prioritize.

**Comment by amirbey** [comment]
spoke with @jseppi who raised this issue and thinks its not worth fixing b/c the error is readable .... and is more hassle then its worth ... moving to backlog

this issue only occurs when credentials are expired

**Comment by wslack** [comment]
Annoying but not otherwise a huge deal; closing.
